#!/usr/bin/python3
"""Factorizes a number into a product of two smaller numbers."""
from sys import argv

def factorize(number):
    """"print a simple descomposition of an integer > 1"""
    x = 2

    if number < 2:
        return
    print()
    print(number, "<- number-bef")
    while number % x:
        x += 1
    print("{:.0f}={:.0f}*{:.0f}".format(number, number / x, x))
    print(number, "<- number-aft")
    print()

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            number = int(line.split('\n')[0])
            factorize(number)
            line = file.readline()
except:
    pass
